#!/usr/bin/env python3
"""
PRIME-Net Swarm Intelligence applied to Project-Beale
=====================================================
Uses a multi-island cooperative swarm of PRIME-Net engines to perform
unsupervised invariant mining and dynamical system identification across
the three Beale Ciphers (B1, B2, B3).

Tests:
  1. Recurrent Autoregressive Law Mining: c_t = f(c_{t-1}, c_{t-2}, c_{t-3}, t)
  2. Consecutive Step Drift Dynamics: Delta c_t = f(Delta c_{t-1}, c_{t-1}, t)
  3. Cross-Cipher Keystream Derivation: Can B1 or B3 be derived from B2?
  4. Modulo / Alphabet Residue Resonances: c_t mod M
"""

import time
import concurrent.futures
import numpy as np
import pandas as pd
from pathlib import Path

from prime_core import run_prime_engine, predict_rpn, _compute_r2

DATA_DIR = Path(__file__).resolve().parent / "data"

def load_cipher(filename):
    with open(DATA_DIR / filename, "r") as f:
        return np.array([int(x) for x in f.read().split()], dtype=np.float64)

# ----------------------------------------------------------------------
# SWARM ENGINE RUNNER
# ----------------------------------------------------------------------
def _swarm_worker(args):
    X_in, y_in, pop, gens, to, seed = args
    return run_prime_engine(
        X_in, y_in,
        pop_size=pop,
        seq_len=63,
        macro_seq_len=15,
        max_generations=gens,
        timeout_sec=to,
        enable_affine=True,
        lambda_penalty=0.005,
        seed=seed,
    )

def run_swarm_search(X, y, num_islands=8, island_pop=64, max_gens=60, timeout_sec=15.0, task_desc=""):
    """
    Run 8 parallel islands across 8 distinct random seeds and select the best discovered invariant.
    """
    seeds = [42 + i * 101 for i in range(num_islands)]
    tasks = []
    for s in seeds:
        tasks.append((X, y, island_pop, max_gens, timeout_sec, s))

    t0 = time.perf_counter()
    with concurrent.futures.ProcessPoolExecutor(max_workers=num_islands) as executor:
        results = list(executor.map(_swarm_worker, tasks))
    elapsed = time.perf_counter() - t0

    # Filter valid
    valid = [r for r in results if r["best_sympy"] is not None and r["train_r2"] > -100]
    best = min(valid, key=lambda r: r["train_mse"]) if valid else results[0]
    unique_formulas = len(set(str(r["best_sympy"]) for r in results))

    return {
        "train_r2": best["train_r2"],
        "train_mse": best["train_mse"],
        "formula": str(best["best_sympy"]),
        "discovery_gen": best["discovery_gen"],
        "latency_sec": elapsed,
        "unique_explorations": unique_formulas,
    }

# ----------------------------------------------------------------------
# EXPERIMENT SUITE
# ----------------------------------------------------------------------
def main():
    print("=" * 110)
    print(" PRIME-NET SWARM CRYPTANALYSIS: PROJECT BEALE (B1, B2, B3)")
    print("=" * 110)

    b1 = load_cipher("b1.txt")
    b2 = load_cipher("b2.txt")
    b3 = load_cipher("b3.txt")

    print(f"[*] Loaded Ciphers: B1 (N={len(b1)}, Max={int(b1.max())}), "
          f"B2 (N={len(b2)}, Max={int(b2.max())}), B3 (N={len(b3)}, Max={int(b3.max())})")

    records = []

    # ------------------------------------------------------------------
    # EXPERIMENT 1: Recurrent Autoregressive Dynamics c_t = f(c_{t-1}, c_{t-2}, c_{t-3}, t)
    # ------------------------------------------------------------------
    print("\n" + "-" * 110)
    print(" [EXPERIMENT 1] Autoregressive Recurrent Law Discovery: c_t = f(c_{t-1}, c_{t-2}, c_{t-3}, t)")
    print(" Goal: Test if any cipher is generated by a deterministic mathematical recurrence vs natural prose lookup.")
    print("-" * 110)

    ciphers = [("B1 (Unsolved Location)", b1), ("B2 (Solved Declaration)", b2), ("B3 (Unsolved Names)", b3)]

    for name, c_seq in ciphers:
        # Build lag features: X = [c_{t-1}, c_{t-2}, c_{t-3}, t/N]
        L = len(c_seq)
        X_lags = []
        y_target = []
        for t in range(3, L):
            X_lags.append([c_seq[t-1], c_seq[t-2], c_seq[t-3], t / L])
            y_target.append(c_seq[t])

        X_lags = np.array(X_lags)
        y_target = np.array(y_target)

        # Run Swarm
        res = run_swarm_search(X_lags, y_target, num_islands=8, island_pop=64, max_gens=60, timeout_sec=15.0)
        print(f"  {name:<30} | R2: {res['train_r2']:<8.4f} | MSE: {res['train_mse']:<10.2f} | Time: {res['latency_sec']:.2f}s")
        print(f"    -> Formula: {res['formula']}")
        print(f"    -> Unique explored hypotheses: {res['unique_explorations']}/8 islands\n")

        records.append({
            "experiment": "1. Autoregressive Recurrence",
            "target": name,
            "r2": res["train_r2"],
            "mse": res["train_mse"],
            "formula": res["formula"],
            "latency": res["latency_sec"],
        })

    # ------------------------------------------------------------------
    # EXPERIMENT 2: Consecutive Step Size & Drift Dynamics: Delta c_t = f(Delta c_{t-1}, c_{t-1}, t)
    # ------------------------------------------------------------------
    print("-" * 110)
    print(" [EXPERIMENT 2] Step-Size & Drift Dynamics: Delta c_t = f(Delta c_{t-1}, c_{t-1}, t)")
    print(" Goal: Mine the mathematical law behind B3's extreme +0.60 autocorrelation and local step drift.")
    print("-" * 110)

    for name, c_seq in ciphers:
        diffs = np.diff(c_seq)
        L = len(diffs)
        X_diff = []
        y_diff = []
        for t in range(2, L):
            X_diff.append([diffs[t-1], diffs[t-2], c_seq[t-1], t / L])
            y_diff.append(diffs[t])

        X_diff = np.array(X_diff)
        y_diff = np.array(y_diff)

        res = run_swarm_search(X_diff, y_diff, num_islands=8, island_pop=64, max_gens=60, timeout_sec=15.0)
        print(f"  {name:<30} | R2: {res['train_r2']:<8.4f} | MSE: {res['train_mse']:<10.2f} | Time: {res['latency_sec']:.2f}s")
        print(f"    -> Formula: {res['formula']}\n")

        records.append({
            "experiment": "2. Step Drift Dynamics",
            "target": name,
            "r2": res["train_r2"],
            "mse": res["train_mse"],
            "formula": res["formula"],
            "latency": res["latency_sec"],
        })

    # ------------------------------------------------------------------
    # EXPERIMENT 3: Cross-Cipher Transfer Functions (Did Beale derive B1 or B3 from B2?)
    # ------------------------------------------------------------------
    print("-" * 110)
    print(" [EXPERIMENT 3] Cross-Cipher Coupling: Is B1 or B3 a Mathematical Transformation of B2?")
    print(" Goal: Check if B1(t) = f(B2(t), t) or B3(t) = f(B2(t), t) (Keystream / Pad Reuse).")
    print("-" * 110)

    pairs = [
        ("B1 from B2 (Location from DOI Cipher)", b2, b1),
        ("B3 from B2 (Names from DOI Cipher)", b2, b3),
        ("B3 from B1 (Names from Location Cipher)", b1, b3)
    ]

    for label, src, dst in pairs:
        min_len = min(len(src), len(dst))
        t_norm = np.linspace(0, 1, min_len).reshape(-1, 1)
        X_pair = np.hstack([src[:min_len].reshape(-1, 1), t_norm])
        y_pair = dst[:min_len]

        res = run_swarm_search(X_pair, y_pair, num_islands=8, island_pop=64, max_gens=60, timeout_sec=15.0)
        print(f"  {label:<42} | R2: {res['train_r2']:<8.4f} | MSE: {res['train_mse']:<10.2f} | Time: {res['latency_sec']:.2f}s")
        print(f"    -> Formula: {res['formula']}\n")

        records.append({
            "experiment": "3. Cross-Cipher Coupling",
            "target": label,
            "r2": res["train_r2"],
            "mse": res["train_mse"],
            "formula": res["formula"],
            "latency": res["latency_sec"],
        })

    # ------------------------------------------------------------------
    # EXPERIMENT 4: Modulo Alphabet / Grid Resonances (c_t mod 26, c_t mod 100)
    # ------------------------------------------------------------------
    print("-" * 110)
    print(" [EXPERIMENT 4] Modulo Residue Regularity: Alphabet Space (mod 26)")
    print(" Goal: Determine if residue classes mod 26 follow an algebraic sequence.")
    print("-" * 110)

    for name, c_seq in ciphers:
        y_mod26 = c_seq % 26
        L = len(y_mod26)
        t_steps = np.arange(L).reshape(-1, 1)
        X_mod = np.hstack([t_steps, np.roll(y_mod26, 1).reshape(-1, 1)])[1:]
        y_target = y_mod26[1:]

        res = run_swarm_search(X_mod, y_target, num_islands=8, island_pop=64, max_gens=60, timeout_sec=15.0)
        print(f"  {name:<30} mod 26 | R2: {res['train_r2']:<8.4f} | MSE: {res['train_mse']:<10.2f} | Time: {res['latency_sec']:.2f}s")
        print(f"    -> Formula: {res['formula']}\n")

        records.append({
            "experiment": "4. Modulo 26 Residue",
            "target": name,
            "r2": res["train_r2"],
            "mse": res["train_mse"],
            "formula": res["formula"],
            "latency": res["latency_sec"],
        })

    df = pd.DataFrame(records)
    df.to_csv("beale_swarm_findings.csv", index=False)
    print("=" * 110)
    print(" BEALE SWARM CRYPTANALYSIS COMPLETE! Output saved to beale_swarm_findings.csv")
    print("=" * 110)

if __name__ == "__main__":
    main()
